channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - apptools=4.5.0
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-countclust=1.14.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicranges=1.38.0
  - bioconductor-graph=1.64.0
  - bioconductor-gseabase=1.48.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-mast=1.12.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-singlecellexperiment=1.8.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - bleach=3.1.0
  - blosc=1.17.0
  - bwidget=1.9.13
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.13.2
  - cloudpickle=1.1.1
  - colormath=3.0.0
  - colorspacious=1.1.2
  - configobj=5.0.6
  - curl=7.65.3
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - envisage=4.8.0
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - future=0.18.2
  - gast=0.2.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.58.3
  - gmp=6.1.2
  - google-pasta=0.1.8
  - graphite2=1.3.13
  - grpcio=1.23.0
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - igraph=0.7.1
  - importlib_metadata=1.1.0
  - ipykernel=5.2.0
  - ipython=7.10.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9c
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - leidenalg=0.7.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.0
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libllvm9=9.0.0
  - libnetcdf=4.7.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.9.1
  - libxml2=2.9.10
  - llvmlite=0.30.0
  - louvain=0.6.1
  - lz4-c=1.8.3
  - lzo=2.10
  - make=4.2.1
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mayavi=4.7.1
  - mistune=0.8.4
  - mock=3.0.5
  - more-itertools=7.2.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.4
  - notebook=6.0.1
  - nspr=4.23
  - nss=3.47
  - numba=0.46.0
  - numexpr=2.7.0
  - numpy=1.17.3
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pandas=0.25.3
  - pandoc=2.8.0.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - pixman=0.38.0
  - pot=0.6.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.11.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycairo=1.18.2
  - pycparser=2.19
  - pyface=6.1.2
  - pygments=2.5.2
  - pyparsing=2.4.5
  - pyqt=5.12.3
  - pyrsistent=0.15.6
  - pytables=3.6.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - python-igraph=0.7.1.post7
  - python_abi=3.7
  - pytz=2019.3
  - pyyaml=5.1.2
  - pyzmq=18.1.1
  - qt=5.12.5
  - qtconsole=4.6.0
  - r-abind=1.4_5
  - r-ape=5.3
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bibtex=0.4.2
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-callr=3.4.3
  - r-catools=1.17.1.3
  - r-cli=1.1.0
  - r-clipr=0.7.0
  - r-clisymbols=1.2.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-cowplot=1.0.0
  - r-crayon=1.3.4
  - r-crosstalk=1.0.0
  - r-curl=4.3
  - r-data.table=1.12.6
  - r-dbi=1.1.0
  - r-desc=1.2.0
  - r-devtools=2.0.2
  - r-digest=0.6.23
  - r-doparallel=1.0.15
  - r-dplyr=0.8.3
  - r-dqrng=0.2.1
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.0
  - r-farver=2.0.1
  - r-fastmap=1.0.1
  - r-fitdistrplus=1.0_14
  - r-flexmix=2.3_15
  - r-fnn=1.1.3
  - r-foreach=1.4.7
  - r-formatr=1.7
  - r-fs=1.4.1
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.15.1
  - r-future.apply=1.3.0
  - r-gam=1.16.1
  - r-gbrd=0.4_11
  - r-gdata=2.18.0
  - r-ggally=1.4.0
  - r-ggplot2=3.2.1
  - r-ggrepel=0.8.1
  - r-ggridges=0.5.1
  - r-gh=1.1.0
  - r-git2r=0.26.1
  - r-globals=0.12.4
  - r-glue=1.3.1
  - r-gplots=3.0.1.1
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.1
  - r-hdf5r=1.3.2
  - r-hexbin=1.28.0
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.4.0
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-ica=1.0_2
  - r-igraph=1.2.4.2
  - r-ini=0.3.1
  - r-irdisplay=0.7
  - r-irkernel=1.0.2
  - r-irlba=2.3.3
  - r-iterators=1.0.12
  - r-itertools=0.1_3
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.27
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-later=1.0.0
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-leiden=0.3.1
  - r-lifecycle=0.1.0
  - r-listenv=0.7.0
  - r-lle=1.1
  - r-lmtest=0.9_37
  - r-locfit=1.5_9.1
  - r-loomr=0.2.0_beta
  - r-lsei=1.2_0
  - r-magrittr=1.5
  - r-maptpx=1.9_2
  - r-markdown=1.1
  - r-mass=7.3_51.4
  - r-matrix=1.2_17
  - r-matrixmodels=0.4_1
  - r-matrixstats=0.55.0
  - r-memoise=1.1.0
  - r-metap=1.1
  - r-mgcv=1.8_29
  - r-mime=0.7
  - r-modeltools=0.2_23
  - r-munsell=0.5.0
  - r-nlme=3.1_141
  - r-nmf=0.21.0
  - r-nnet=7.3_13
  - r-npsurv=0.4_0
  - r-openssl=1.4.1
  - r-pbapply=1.4_2
  - r-pbdzmq=0.3_3
  - r-permute=0.9_5
  - r-pheatmap=1.0.12
  - r-picante=1.8.1
  - r-pillar=1.4.2
  - r-pkgbuild=1.0.6
  - r-pkgconfig=2.0.3
  - r-pkgload=1.0.2
  - r-pkgmaker=0.27
  - r-plogr=0.2.0
  - r-plotly=4.9.1
  - r-plyr=1.8.4
  - r-png=0.1_7
  - r-prettyunits=1.1.0
  - r-princurve=2.1.4
  - r-processx=3.4.2
  - r-progress=1.2.2
  - r-promises=1.1.0
  - r-ps=1.3.2
  - r-purrr=0.3.3
  - r-quantreg=5.52
  - r-r.methodss3=1.7.1
  - r-r.oo=1.23.0
  - r-r.utils=2.9.0
  - r-r6=2.4.1
  - r-randomforest=4.6_14
  - r-rann=2.6.1
  - r-rcmdcheck=1.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.3
  - r-rcppannoy=0.0.14
  - r-rcppeigen=0.3.3.7.0
  - r-rcppparallel=4.4.4
  - r-rcppprogress=0.4.1
  - r-rcurl=1.98_1.1
  - r-rdpack=0.11_0
  - r-registry=0.5_1
  - r-remotes=2.1.1
  - r-repr=1.0.1
  - r-reshape=0.8.8
  - r-reshape2=1.4.3
  - r-reticulate=1.13
  - r-rlang=0.4.2
  - r-rngtools=1.4
  - r-rocr=1.0_7
  - r-rprojroot=1.3_2
  - r-rspectra=0.15_0
  - r-rsqlite=2.1.1
  - r-rstudioapi=0.11
  - r-rsvd=1.0.2
  - r-rtsne=0.15
  - r-scales=1.1.0
  - r-scatterplot3d=0.3_41
  - r-sctransform=0.2.0
  - r-sdmtools=1.1_221.2
  - r-sessioninfo=1.1.1
  - r-seurat=3.1.1
  - r-shiny=1.4.0
  - r-sitmo=2.0.1
  - r-slam=0.1_47
  - r-snow=0.4_3
  - r-snowfall=1.84_6.1
  - r-som=0.3_5.1
  - r-sourcetools=0.1.7
  - r-sparsem=1.77
  - r-squarem=2020.2
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.3
  - r-tibble=2.1.3
  - r-tidyr=1.0.0
  - r-tidyselect=0.2.5
  - r-tsne=0.1_3
  - r-umap=0.2.3.1
  - r-usethis=1.5.0
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-uwot=0.1.4
  - r-vctrs=0.2.0
  - r-vegan=2.5_6
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.1.2
  - r-xfun=0.12
  - r-xml=3.99_0.3
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - r-zoo=1.8_6
  - readline=8.0
  - rpy2=3.1.0
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - seaborn=0.9.0
  - sed=4.7
  - send2trash=1.5.0
  - setuptools=42.0.2
  - simplegeneric=0.8.1
  - six=1.13.0
  - spectra=0.0.11
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tbb=2019.9
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - traits=5.2.0
  - traitsui=6.1.3
  - tzlocal=2.0.0
  - vtk=8.2.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - anndata==0.6.22.post1
    - bokeh==2.0.2
    - click==7.0
    - cmake==3.15.3
    - colorcet==2.0.2
    - cython==0.29.14
    - dask==2.9.2
    - docopt==0.6.2
    - fa2==0.3.5
    - fcsparser==0.2.0
    - fisher==0.1.9
    - forceatlas2-python==1.0
    - hnswlib==0.3.4
    - holoviews==1.13.2
    - hvplot==0.5.2
    - lightgbm==2.2.1
    - loompy==3.0.6
    - louvain-github==0.6.1.post1
    - matplotlib==3.0.3
    - multicoretsne==0.1
    - multicoretsne-modified==0.1.post2
    - natsort==6.2.0
    - packaging==19.2
    - panel==0.9.5
    - param==1.9.3
    - pegasuspy==0.17.1
    - plotly==4.6.0
    - pluggy==0.13.1
    - psutil==5.6.7
    - py==1.8.0
    - pyarrow==0.17.0
    - pybind11==2.5.0
    - pyct==0.4.6
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytest==5.3.1
    - pyviz-comms==0.7.4
    - retrying==1.3.3
    - scanpy==1.4.4.post1
    - scikit-misc==0.1.1
    - scplot==0.0.16
    - toolz==0.10.0
    - tqdm==4.39.0
    - typing-extensions==3.7.4.2
    - umap-learn==0.3.10
    - wot==1.0.5
    - xlsxwriter==1.2.8

